[build]
  functions = "backend"
  publish = "frontend/dist"
  command = "npm run build:all"

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/distAdminService/index"
  status = 200

[[redirects]]
  from = "/api/users/*"
  to = "/.netlify/functions/distUserService/index"
  status = 200



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
